# PROGRAM
<program> ::= "prog" <IDENTIFIER> ":" <block> ":)"

# BLOCK
<block> ::= <stmt> <block> | "done"

# STATEMENTS
<stmt> ::= <var_decl_stmt> | <assignment_stmt> | <if_else_stmt> | <while_stmt>
## variable declaration
<var_decl_stmt> ::= <DATA_TYPE> <IDENTIFIER> ";"
## assignment
<assignment_stmt> ::= "set" <IDENTIFIER> "=" <expr> ";"
## if else
<if_else_stmt> ::= "if" "(" <expr> ")" ":" <block> <else_stmt>
<else_stmt> ::= "else" ":" <block> | <EMPTY>
## while
<while_stmt> ::= "while" "(" <expr> ")" ":" <block>

# EXPRESSIONS
<expr> ::= <term> | <expr> <expr_op> <term>
<term> ::= <factor> | <term> <term_op> <factor>
<factor> ::= <IDENTIFIER> | <LITERAL> | "(" <expr> ")" | "!" <factor> | "-" <factor>

<expr_op> ::= "+" | "-" | "||" | "&&"
<term_op> ::= "*" | "/" | "==" | "!=" | ">" | ">=" | "<" | "<="
